reset password
Eco-Gest/Backend-Laravel pull request #11
Opened 2024-04-08 09:29 UTC by AugustinSeguin

2024-05-03 12:45 UTC, eleonoreeuzenes requested changes

2024-05-03 12:45 UTC, eleonoreeuzenes commented on app/Http/Controllers/Api/AuthenticationController.php
> +    $user = User::where('email', $validatedData['email'])->firstOrFail();
J'ai une 404 quand le mail n'existe pas est-ce que ce serait possible d'avoir un erreur 400 avec un message "email doesn't exists" pour remonter que le compte n'existe pas ? ou peut être c'est une faille de sécu de donner cette info ?

2024-05-03 15:49 UTC, AugustinSeguin commented on app/Http/Controllers/Api/AuthenticationController.php
> +    $user = User::where('email', $validatedData['email'])->firstOrFail();
c'est normal je trouve :) on trouve pas la ressource => donc 404

2024-05-03 20:43 UTC, eleonoreeuzenes commented on app/Http/Controllers/Api/AuthenticationController.php
> +      'confirm_password' => 'required|same:new_password',
un peu hs mais je ne sais pas où remonter l'info. Dans register on ne  fait la vérification de confirm_password, il faudrait peut être non ?

2024-05-09 13:06 UTC, eleonoreeuzenes approved these changes

2024-05-09 13:06 UTC, merged