PROD DEPLOY
Eco-Gest/Backend-Laravel pull request #32
Opened 2024-05-30 09:38 UTC by AugustinSeguin

D'abord merge les 2 PR

2024-05-30 15:56 UTC, eleonoreeuzenes commented on Makefile
> +public/build/manifest.json: package.json
à quoi nous sert la partie node.js de notre API ?
on utilise une de ces dépendences ?
    "devDependencies": {
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.8.0",
        "vite": "^4.0.0"
    }

2024-05-31 09:38 UTC, AugustinSeguin commented on Makefile
> +public/build/manifest.json: package.json
je me suis renseigné c'est utile pour nos vues donc dans notre cas les mails

2024-06-05 10:51 UTC, eleonoreeuzenes approved these changes

2024-06-05 12:18 UTC, eleonoreeuzenes requested changes
le fichier package.json ne sert à rien

2024-06-19 18:55 UTC, eleonoreeuzenes approved these changes

2024-06-19 18:56 UTC, eleonoreeuzenes commented
@AugustinSeguin on la merge ?

2024-06-20 10:19 UTC, merged