Cache redis
Eco-Gest/Backend-Laravel pull request #35
Opened 2024-06-12 11:45 UTC by eleonoreeuzenes

Fix du cache testé via postman

**Modifications :** 

- Autoriser l'accès au cache que si on a les droits

`    if (Cache::has('user_' . $userId)) {
      $user = User::findOrFail($userId);
      if ($this->userService->checkIfCanAccessToResource($user->id) && $this->userService->isUserUnblocked($user->id)) {
        return response()->json(Cache::get('user_' . $userId));
      } 
    }`
    

-   Mise en cache que si on a les full droits sur un contenu

`    if ($this->userService->checkIfCanAccessToResource($user->id) && $this->userService->isUserUnblocked($user->id)) {
        Cache::put('user_' . $userId, $user, now()->addMinutes(60));
    }`

2024-06-12 12:00 UTC, AugustinSeguin requested changes

2024-06-12 12:00 UTC, AugustinSeguin commented on app/Http/Controllers/Api/PostController.php
> +            $post = Post::where('id', $id)->firstOrFail();
justement l'idée est de ne avoir cette ligne. Car là tu refais un appel en BDD et c'est dommage. Il doit exister une fonction (https://laravel.com/docs/11.x/cache#cache-usage) comme ça :
$post = Cache::get('post_'/$id);
et normalement $post->author_id devrait marcher ;) (sinon $post['author_id'];
et c'est valable pour toutes nos fonctions utilisant le cache

2024-06-13 09:09 UTC, eleonoreeuzenes commented on app/Http/Controllers/Api/PostController.php
> +            $post = Post::where('id', $id)->firstOrFail();
J'ai mis à jour le code en suivant tes recommendations, il reste l'appel pour vérifier les droits de l'utilisateur mais en testant sur postman je vois que ça divise tout de même par 2 la durée de l'appel à l'api .

2024-06-13 14:00 UTC, AugustinSeguin requested changes

2024-06-19 10:22 UTC, AugustinSeguin approved these changes

2024-06-19 10:22 UTC, merged